input_data = open("input.txt","r")
data = input_data.read()
data = data.split()
output_data = open("output.txt","w")
output_data.write( str(10 - int(data[0])) + " " + str(10 - int(data[1])))
input_data.close()
